version: "3"
services:
  app:
    build: .
    image: app:ror5.2
    command: rails server
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgres
  postgres:
    image: postgres:11.1
    ports:
      - "5432"
